version: '2'

services:

  tor-proxy:
    image: jcorgan/tor-proxy

    ports:
      - "127.0.0.1:9050:9050/tcp"
      - "127.0.0.1:9040:9040/tcp"
      - "127.0.0.1:5300:5300/udp"

    volumes:
      - "/opt/tor/etc:/etc/tor"
      - "/opt/tor/var:/var/lib/tor"
